frontend/js/servicos.js

[fix/front-end] corrige envio de valores como string ao tentar salvar servico

---

frontend/js/servicos.js
frontend/pages/servicos.html

[feat/front-end] Implementa alerta para serviços

---

backend/src/main/java/com/optimiza/clickbarber/config/WebConfig.java
backend/src/main/java/com/optimiza/clickbarber/controller/BarbeiroController.java
backend/src/main/java/com/optimiza/clickbarber/exception/GlobalExceptionHandler.java
backend/src/main/java/com/optimiza/clickbarber/model/Barbearia.java
backend/src/main/java/com/optimiza/clickbarber/model/Barbeiro.java
backend/src/main/java/com/optimiza/clickbarber/model/dto/barbeiro/BarbeiroAtualizarDto.java
backend/src/main/java/com/optimiza/clickbarber/repository/BarbeiroRepository.java
backend/src/main/java/com/optimiza/clickbarber/service/BarbeiroService.java
backend/src/main/java/com/optimiza/clickbarber/service/ServicoService.java
backend/src/main/java/com/optimiza/clickbarber/utils/Constants.java
backend/src/main/resources/db/migration/V3__cria_tabela_barbeiros.sql

[SB-10](https://rafabrunofelixs-team.monday.com/boards/6687111724/views/145457529)
Implementa endpoints para Barbeiro
- Endpoints:
- Buscar barbeiro por id: GET - /barbeiros/{id}
- Buscar barbeiros pelo id da barbearia: GET - /barbeiros/barbearia/{id}
- Cadastrar barbeiro: POST - /barbeiros
- Atualizar barbeiro: PUT - /barbeiros
- Deletar barbeiro por id: DELETE - /barbeiros/{id}

[feat/backend] SB-10: Implementa endpoints para Barbeiro

---

backend/src/main/java/com/optimiza/clickbarber/controller/AutenticacaoController.java
backend/src/main/java/com/optimiza/clickbarber/exception/GlobalExceptionHandler.java
backend/src/main/java/com/optimiza/clickbarber/model/Usuario.java
backend/src/main/java/com/optimiza/clickbarber/model/dto/usuario/UsuarioCadastroDto.java
backend/src/main/java/com/optimiza/clickbarber/model/dto/usuario/UsuarioDto.java
backend/src/main/java/com/optimiza/clickbarber/model/dto/usuario/UsuarioMapper.java
backend/src/main/java/com/optimiza/clickbarber/repository/UsuarioRepository.java
backend/src/main/java/com/optimiza/clickbarber/service/AutenticacaoService.java
backend/src/main/java/com/optimiza/clickbarber/service/UsuarioService.java
backend/src/main/java/com/optimiza/clickbarber/utils/Constants.java
backend/src/main/resources/db/migration/V4__cria_tabela_usuarios.sql

[SB-11](https://rafabrunofelixs-team.monday.com/boards/6687111724/views/145457529)
﻿Implementar endpoints para autenticação e criar tabela no banco para Usuários.﻿
﻿Endpoints:
- AutenticacaoController:
- login usuário: POST - auth/usuarios/login
- cadastrar usuário: POST - auth/usuarios/cadastrar

[feat/backend] SB-11: Implementa endpoints para login e cadastrar Usuario

---

frontend-barbearia/public/js/agendamentos.js
frontend-barbearia/public/js/clientes.js
frontend-barbearia/public/pages/agendamentos.html
frontend-barbearia/public/pages/clientes.html

[Refac/Front-End] Refatorações no Front-End

---

backend/src/main/java/com/optimiza/clickbarber/controller/BarbeariaController.java
backend/src/main/java/com/optimiza/clickbarber/repository/BarbeariaRepository.java
backend/src/main/java/com/optimiza/clickbarber/service/BarbeariaService.java
backend/src/main/java/com/optimiza/clickbarber/utils/Constants.java
backend/src/test/java/com/optimiza/clickbarber/controller/BarbeariaControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/service/BarbeariaServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/service/ClienteServiceTest.java

[CB-17](https://rafabrunofelix.atlassian.net/browse/CB-17)

[feat/backend] CB-17: Implementa endpoint para buscar barbearias pelo nome

---

backend/src/test/java/com/optimiza/clickbarber/controller/AgendamentoControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/controller/AutenticacaoControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/controller/BarbeariaControllerTest.kt
backend/src/test/java/com/optimiza/clickbarber/controller/BarbeiroControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/controller/ServicoControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/service/AutenticacaoServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/service/BarbeariaServiceTest.java

[CB-19](https://rafabrunofelix.atlassian.net/browse/CB-19)

[refactor/backend] CB-19: Implementa testes unitários para quando buscar todas as Barbearias

---

backend/src/test/java/com/optimiza/clickbarber/controller/AgendamentoControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/controller/AutenticacaoControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/controller/BarbeariaControllerTest.kt
backend/src/test/java/com/optimiza/clickbarber/controller/BarbeiroControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/controller/ServicoControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/service/AgendamentoServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/service/AutenticacaoServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/service/BarbeariaServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/service/BarbeiroServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/service/ClienteServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/service/ServicoServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/service/UsuarioServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/utils/TestDataFactory.java

[CB-26](https://rafabrunofelix.atlassian.net/browse/CB-26)

[refactor/backend] CB-26: Implementa TestFactory para centralizar a criação de classes nos testes unitários

---

frontend-cliente/package-lock.json
frontend-cliente/package.json
frontend-cliente/src/api/ApiClient.ts
frontend-cliente/src/api/ApiResponse.ts
frontend-cliente/src/api/Constants.ts
frontend-cliente/src/components/SearchBar.tsx
frontend-cliente/src/pages/Inicio.tsx
frontend-cliente/src/services/BarbeariaService.ts

[CB-27](https://rafabrunofelix.atlassian.net/browse/CB-27)

[feat/frontend-cliente] CB-27: Implementa ApiClient

---

backend/src/main/java/com/optimiza/clickbarber/utils/Constants.kt
backend/src/test/java/com/optimiza/clickbarber/controller/AgendamentoControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/controller/BarbeariaControllerTest.kt
backend/src/test/java/com/optimiza/clickbarber/controller/ClienteControllerTest.kt
backend/src/test/java/com/optimiza/clickbarber/service/AgendamentoServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/service/AutenticacaoServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/service/ClienteServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/utils/TestDataFactory.java

[CB-28](https://rafabrunofelix.atlassian.net/browse/CB-28)

[refactor/backend] CB-28: Implementa teste unitário para ClienteController

---

backend/src/main/java/com/optimiza/clickbarber/config/JwtRequestFilter.java

[CB-30](https://rafabrunofelix.atlassian.net/browse/CB-30)

[fix/backend] CB-30: Permite frontend do cliente fazer requisições ao backend localmente sem token

---

backend/pom.xml

[CB-31](https://rafabrunofelix.atlassian.net/browse/CB-31)

[config/backend] CB-31: Remove dependência do docker-compose

---

backend/src/main/java/com/optimiza/clickbarber/model/dto/barbeiro/BarbeiroDto.java
backend/src/main/java/com/optimiza/clickbarber/model/dto/barbeiro/BarbeiroMapper.java
backend/src/main/java/com/optimiza/clickbarber/service/BarbeiroService.java
backend/src/test/java/com/optimiza/clickbarber/service/AutenticacaoServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/service/BarbeiroServiceTest.java

[CB-33](https://rafabrunofelix.atlassian.net/browse/CB-33)

[fix/backend] CB-33: Alteração na resposta ao fazer login com Barbeiro

---

backend/src/main/java/com/optimiza/clickbarber/model/dto/barbearia/BarbeariaMapper.java
backend/src/main/java/com/optimiza/clickbarber/model/dto/barbearia/BarbeariaRespostaLoginDto.java
backend/src/main/java/com/optimiza/clickbarber/model/dto/barbeiro/BarbeiroDto.java
backend/src/main/java/com/optimiza/clickbarber/model/dto/barbeiro/BarbeiroMapper.java
backend/src/main/java/com/optimiza/clickbarber/service/AutenticacaoService.java
backend/src/main/java/com/optimiza/clickbarber/service/BarbeariaService.java
backend/src/test/java/com/optimiza/clickbarber/controller/BarbeiroControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/service/AutenticacaoServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/service/BarbeiroServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/utils/TestDataFactory.java

[CB-32](https://rafabrunofelix.atlassian.net/browse/CB-32)

[refactor/backend] CB-32: Altera resposta ao buscar barbearia por id externo e ao fazer login

---

backend/src/main/java/com/optimiza/clickbarber/controller/ServicoController.java
backend/src/main/java/com/optimiza/clickbarber/model/dto/servico/ServicoCadastroDto.java
backend/src/main/java/com/optimiza/clickbarber/model/dto/servico/ServicoMapper.java
backend/src/main/java/com/optimiza/clickbarber/repository/ServicoRepository.java
backend/src/main/java/com/optimiza/clickbarber/service/ServicoService.java
backend/src/test/java/com/optimiza/clickbarber/controller/ServicoControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/service/ServicoServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/utils/TestDataFactory.java
frontend-admin/src/models/Servico.ts
frontend-admin/src/pages/Servicos.tsx
frontend-admin/src/routes/index.tsx
frontend-admin/src/services/AutenticacaoService.ts
frontend-admin/src/services/ServicoService.ts

[CB-38](https://rafabrunofelix.atlassian.net/browse/CB-38)

[feat/frontend-admin] CB-38 - Implementa página de serviços

---

backend/src/main/java/com/optimiza/clickbarber/controller/BarbeiroController.java
backend/src/main/java/com/optimiza/clickbarber/repository/BarbeiroRepository.java
backend/src/main/java/com/optimiza/clickbarber/service/BarbeiroService.java
backend/src/test/java/com/optimiza/clickbarber/controller/BarbeiroControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/service/BarbeiroServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/utils/TestDataFactory.java
frontend-admin/src/models/Barbeiro.ts
frontend-admin/src/pages/Barbeiros.tsx
frontend-admin/src/routes/index.tsx
frontend-admin/src/services/BarbeiroService.ts

[CB-39](https://rafabrunofelix.atlassian.net/browse/CB-39)

[feat/frontend-admin] CB-39 - Implementa página de barbeiros da barbearia

---

backend/src/main/java/com/optimiza/clickbarber/controller/AgendamentoController.java
backend/src/main/java/com/optimiza/clickbarber/model/dto/agendamento/AgendamentoMapper.java
backend/src/main/java/com/optimiza/clickbarber/model/dto/agendamento/AgendamentoReduzidoDto.java
backend/src/main/java/com/optimiza/clickbarber/repository/AgendamentoRepository.java
backend/src/main/java/com/optimiza/clickbarber/service/AgendamentoService.java
backend/src/main/java/com/optimiza/clickbarber/utils/Constants.kt
backend/src/test/java/com/optimiza/clickbarber/service/AgendamentoServiceTest.java
frontend-admin/package-lock.json
frontend-admin/package.json
frontend-admin/src/components/Calendario.tsx
frontend-admin/src/components/Error.tsx
frontend-admin/src/components/Loading.tsx
frontend-admin/src/css/Calendar.css
frontend-admin/src/models/Agendamento.ts
frontend-admin/src/models/Cliente.ts
frontend-admin/src/pages/Agendamentos.tsx
frontend-admin/src/routes/index.tsx
frontend-admin/src/services/AgendamentoService.ts

[CB-40](https://rafabrunofelix.atlassian.net/browse/CB-40)

[refac/backend] CB-40: Refatora Agendamento para buscar pelo id externo da Barbearia

---

backend/src/test/java/com/optimiza/clickbarber/controller/AgendamentoControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/service/AgendamentoServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/utils/TestDataFactory.java

[CB-40](https://rafabrunofelix.atlassian.net/browse/CB-40)

[refactor/backend] CB-40: Implementa testes unitários em AgendamentoController e AgendamentoService

---

backend/src/main/java/com/optimiza/clickbarber/exception/EntidadeNaoPerteceABarbeariaException.kt
backend/src/main/java/com/optimiza/clickbarber/service/AgendamentoService.java
backend/src/main/java/com/optimiza/clickbarber/utils/Constants.kt
backend/src/test/java/com/optimiza/clickbarber/service/AgendamentoServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/service/AutenticacaoServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/utils/TestDataFactory.java

[CB-46](https://rafabrunofelix.atlassian.net/browse/CB-46)

[fix/backend] CB-46: Valida serviços e barbeiros ao cadastrar agendamento

---

backend/src/main/java/com/optimiza/clickbarber/controller/BarbeariaController.kt
backend/src/main/java/com/optimiza/clickbarber/model/servico/dto/ServicoCadastroDto.java
backend/src/main/java/com/optimiza/clickbarber/model/servico/dto/ServicoMapper.java
backend/src/main/java/com/optimiza/clickbarber/service/BarbeariaService.java
backend/src/main/java/com/optimiza/clickbarber/service/ServicoService.java
backend/src/test/java/com/optimiza/clickbarber/service/ServicoServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/utils/TestDataFactory.java
frontend-admin/src/models/Servico.ts
frontend-admin/src/pages/Servicos.tsx
frontend-admin/src/services/ServicoService.ts

[CB-55](https://rafabrunofelix.atlassian.net/browse/CB-55)

[feat/frontend] CB-55: Implementa cadastro de serviços

---

backend/src/main/java/com/optimiza/clickbarber/model/barbeiro/dto/BarbeiroCadastroDto.java
backend/src/main/java/com/optimiza/clickbarber/service/BarbeiroService.java
frontend-admin/src/models/Barbeiro.ts
frontend-admin/src/pages/Barbeiros.tsx
frontend-admin/src/services/AutenticacaoService.ts

[CB-56](https://rafabrunofelix.atlassian.net/browse/CB-56)

[feat/frontend] CB-56: Implementa cadastro de barbeiros

---

backend/src/main/java/com/optimiza/clickbarber/controller/AgendamentoController.java
backend/src/main/java/com/optimiza/clickbarber/model/agendamento/dto/AgendamentoDto.java
backend/src/main/java/com/optimiza/clickbarber/model/agendamento/dto/AgendamentoMapper.java
backend/src/main/java/com/optimiza/clickbarber/repository/AgendamentoRepository.kt
backend/src/main/java/com/optimiza/clickbarber/service/AgendamentoService.java
backend/src/test/java/com/optimiza/clickbarber/controller/AgendamentoControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/service/AgendamentoServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/utils/TestDataFactory.java
frontend-admin/src/components/AgendamentoModal.tsx
frontend-admin/src/components/Calendario.tsx
frontend-admin/src/components/Loading.tsx
frontend-admin/src/models/Agendamento.ts
frontend-admin/src/models/Cliente.ts
frontend-admin/src/pages/Agendamentos.tsx
frontend-admin/src/services/AgendamentoService.ts

[CB-54](https://rafabrunofelix.atlassian.net/browse/CB-54)

[feat/frontend] CB-54: Implementar visualizar detalhes do Agendamento

---

backend/src/main/java/com/optimiza/clickbarber/model/agendamento/dto/AgendamentoDto.java
backend/src/main/java/com/optimiza/clickbarber/model/agendamento/dto/AgendamentoMapper.java
backend/src/main/java/com/optimiza/clickbarber/model/barbearia/dto/BarbeariaMapper.java
backend/src/main/java/com/optimiza/clickbarber/model/barbearia/dto/BarbeariaRespostaDto.java
backend/src/main/java/com/optimiza/clickbarber/model/barbeiro/dto/BarbeiroAgendamentoDto.java
backend/src/main/java/com/optimiza/clickbarber/model/barbeiro/dto/BarbeiroMapper.java
backend/src/main/java/com/optimiza/clickbarber/model/barbeiro/dto/BarbeiroRespostaDto.kt
backend/src/main/java/com/optimiza/clickbarber/model/servico/dto/ServicoMapper.java
backend/src/main/java/com/optimiza/clickbarber/service/AgendamentoService.java
backend/src/main/java/com/optimiza/clickbarber/service/BarbeariaService.java
backend/src/test/java/com/optimiza/clickbarber/controller/AgendamentoControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/service/AutenticacaoServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/utils/TestDataFactory.java

[CB-43](https://rafabrunofelix.atlassian.net/browse/CB-43)

[refactor/backend] CB-43: Altera retorno da barbearia e dos serviços e barbeiros ao cadastrar agendamento

---

backend/src/main/java/com/optimiza/clickbarber/model/barbearia/dto/BarbeariaDto.java
backend/src/main/java/com/optimiza/clickbarber/model/barbearia/dto/BarbeariaMapper.java
backend/src/test/java/com/optimiza/clickbarber/controller/AgendamentoControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/service/AgendamentoServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/utils/TestDataFactory.java

[CB-41](https://rafabrunofelix.atlassian.net/browse/CB-41)

[refactor/backend] CB-41: Altera retorno de serviços ao buscar barbearia por id externo

---

frontend-admin/src/pages/Configuracoes.tsx
frontend-admin/src/routes/index.tsx

[CB-60](https://rafabrunofelix.atlassian.net/browse/CB-60)

[feat/frontend-admin] CB-60: Implementa página de configurações

---

frontend-admin/src/components/MenuConfiguracoes.tsx
frontend-admin/src/pages/Configuracoes.tsx
frontend-admin/src/pages/configuracoes/ConfiguracoesNotificacoes.tsx
frontend-admin/src/pages/configuracoes/ConfiguracoesPerfil.tsx
frontend-admin/src/pages/configuracoes/ConfiguracoesPrivacidade.tsx
frontend-admin/src/pages/configuracoes/ConfiguracoesSeguranca.tsx
frontend-admin/src/routes/index.tsx

[CB-61](https://rafabrunofelix.atlassian.net/browse/CB-61)

[feat/frontend-admin] CB-61: Implementa menu página de configurações

---

backend/src/main/java/com/optimiza/clickbarber/config/JwtRequestFilter.java
backend/src/main/java/com/optimiza/clickbarber/config/WebConfig.java
backend/src/main/java/com/optimiza/clickbarber/controller/BarbeariaController.kt
backend/src/main/java/com/optimiza/clickbarber/exception/AtualizacaoEntidadeException.kt
backend/src/main/java/com/optimiza/clickbarber/model/barbearia/dto/BarbeariaAtualizarDto.kt
backend/src/main/java/com/optimiza/clickbarber/model/barbearia/dto/BarbeariaDto.java
backend/src/main/java/com/optimiza/clickbarber/model/barbearia/dto/BarbeariaMapper.java
backend/src/main/java/com/optimiza/clickbarber/model/usuario/Usuario.kt
backend/src/main/java/com/optimiza/clickbarber/service/BarbeariaService.java
backend/src/main/java/com/optimiza/clickbarber/utils/Constants.kt
frontend-admin/src/models/Barbearia.ts
frontend-admin/src/pages/configuracoes/ConfiguracoesPerfil.tsx
frontend-admin/src/services/BarbeariaService.ts

[CB-62](https://rafabrunofelix.atlassian.net/browse/CB-62)

[feat/backend/frontend-admin] CB-62: Implementa endpoint e página para atualizar barbearia

---

frontend-admin/src/pages/configuracoes/ConfiguracoesSeguranca.tsx

[CB-63](https://rafabrunofelix.atlassian.net/browse/CB-63)

[feat/frontend-admin] CB-63 Implementa página de configurações de segurança

---

backend/src/main/java/com/optimiza/clickbarber/controller/ServicoController.java
backend/src/main/java/com/optimiza/clickbarber/service/ServicoService.java
backend/src/test/java/com/optimiza/clickbarber/controller/ServicoControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/service/BarbeariaServiceTest.java
backend/src/test/java/com/optimiza/clickbarber/service/ServicoServiceTest.java
frontend-admin/src/pages/Servicos.tsx
frontend-admin/src/services/ServicoService.ts

[CB-52](https://rafabrunofelix.atlassian.net/browse/CB-52)

[feat/frontend-admin] CB-52: Implementa exclusão de serviços

---

backend/src/main/java/com/optimiza/clickbarber/exception/CadastroAgendamentoException.kt
backend/src/main/java/com/optimiza/clickbarber/exception/GlobalExceptionHandler.java
backend/src/main/java/com/optimiza/clickbarber/service/AgendamentoService.java
frontend-admin/src/components/AgendamentoCadastroModal.tsx

[CB-69](https://rafabrunofelix.atlassian.net/browse/CB-69)

[fix/frontend-admin/backend] CB-69: Corrige erro ao cadastrar agendamento quando data e hora são nulas

---

frontend-admin/package.json
frontend-admin/src/components/AgendamentoCadastroModal.tsx

[CB-75](https://rafabrunofelix.atlassian.net/browse/CB-75)

[feature/frontend-admin] CB-75: Altera ordem de seleção no modal de cadastro de agendamentos

---

backend/src/main/java/com/optimiza/clickbarber/config/AppConfig.kt
backend/src/main/java/com/optimiza/clickbarber/config/PropertiesConfig.kt
backend/src/main/java/com/optimiza/clickbarber/controller/AutenticacaoController.java
backend/src/main/java/com/optimiza/clickbarber/handler/LoginHandlerChain.kt
backend/src/main/java/com/optimiza/clickbarber/model/autenticacao/RespostaLogin.java
backend/src/main/java/com/optimiza/clickbarber/model/barbearia/dto/BarbeariaMapper.java
backend/src/main/java/com/optimiza/clickbarber/model/barbearia/dto/BarbeariaRespostaDto.java
backend/src/main/java/com/optimiza/clickbarber/model/barbeiro/dto/BarbeiroDto.java
backend/src/main/java/com/optimiza/clickbarber/model/barbeiro/dto/BarbeiroMapper.java
backend/src/main/java/com/optimiza/clickbarber/model/cliente/dto/ClienteDto.java
backend/src/main/java/com/optimiza/clickbarber/model/cliente/dto/ClienteMapper.java
backend/src/main/java/com/optimiza/clickbarber/model/usuario/Usuario.kt
backend/src/main/java/com/optimiza/clickbarber/service/AutenticacaoService.java
backend/src/main/java/com/optimiza/clickbarber/utils/Constants.kt
backend/src/test/java/com/optimiza/clickbarber/controller/AutenticacaoControllerTest.java
backend/src/test/java/com/optimiza/clickbarber/service/AutenticacaoServiceTest.java

[CB-79](https://rafabrunofelix.atlassian.net/browse/CB-79)

[fix/frontend-admin] CB-79: Quando usuário tiver role Cliente não poderá acessar o admin

---

backend/src/main/java/com/optimiza/clickbarber/config/WebConfig.java
backend/src/main/java/com/optimiza/clickbarber/controller/FormaPagamentoController.kt
backend/src/main/java/com/optimiza/clickbarber/model/RespostaUtils.java
backend/src/main/java/com/optimiza/clickbarber/model/barbearia/Barbearia.java
backend/src/main/java/com/optimiza/clickbarber/model/formaspagamento/FormaPagamento.kt
backend/src/main/java/com/optimiza/clickbarber/model/formaspagamento/dto/FormaPagamentoAtualizarDto.kt
backend/src/main/java/com/optimiza/clickbarber/model/formaspagamento/dto/FormaPagamentoCadastroDto.kt
backend/src/main/java/com/optimiza/clickbarber/model/formaspagamento/dto/FormaPagamentoRespostaDto.kt
backend/src/main/java/com/optimiza/clickbarber/repository/FormaPagamentoRepository.kt
backend/src/main/java/com/optimiza/clickbarber/service/FormaPagamentoService.kt
backend/src/main/java/com/optimiza/clickbarber/utils/Constants.kt
backend/src/main/resources/db/migration/postgres/V11__cria_tabela_formas_pagamento.sql
backend/src/main/resources/db/migration/test/V1_11__cria_tabela_formas_pagamento.sql
frontend-admin/src/components/MenuLateral.tsx
frontend-admin/src/models/FormaPagamento.ts
frontend-admin/src/pages/FormasPagamento.tsx
frontend-admin/src/routes/index.tsx
frontend-admin/src/services/FormaPagamentoService.ts

- CB-81: https://rafabrunofelix.atlassian.net/browse/CB-81
- CB-82: https://rafabrunofelix.atlassian.net/browse/CB-82
Implementação para permitir que Barbearia possa cadastrar, ver, editar e excluir formas de pagamento.

[feat/frontend-admin/backend] CB-81/CB-82 - Implementa página, endpoints e tabela para formas de pagamento

---

backend/pom.xml
backend/src/main/java/com/optimiza/clickbarber/model/agendamento/Agendamento.java
backend/src/main/java/com/optimiza/clickbarber/model/agendamento/dto/AgendamentoCadastroDto.java
backend/src/main/java/com/optimiza/clickbarber/model/agendamento/dto/AgendamentoDto.java
backend/src/main/java/com/optimiza/clickbarber/model/agendamento/dto/AgendamentoMapper.java
backend/src/main/java/com/optimiza/clickbarber/model/formaspagamento/dto/FormaPagamentoMapper.java
backend/src/main/java/com/optimiza/clickbarber/model/usuario/dto/UsuarioAgendamentoDto.java
backend/src/main/java/com/optimiza/clickbarber/model/usuario/dto/UsuarioMapper.java
backend/src/main/java/com/optimiza/clickbarber/service/AgendamentoService.java
backend/src/main/java/com/optimiza/clickbarber/service/BarbeariaService.java
backend/src/main/java/com/optimiza/clickbarber/service/FormaPagamentoService.kt
backend/src/main/java/com/optimiza/clickbarber/service/UsuarioService.java
backend/src/main/resources/db/migration/postgres/V12__adiciona_colunas_forma_pagamento_e_created_by_em_agendamentos.sql
backend/src/main/resources/db/migration/test/V1_12__adiciona_colunas_forma_pagamento_e_created_by_em_agendamentos.sql
frontend-admin/package.json
frontend-admin/src/components/AgendamentoCadastroModal.tsx
frontend-admin/src/components/AgendamentoModal.tsx
frontend-admin/src/models/Agendamento.ts
frontend-admin/src/models/Usuario.ts

[CB-80](https://rafabrunofelix.atlassian.net/browse/CB-80)

[feat/backend/frontend-admin] CB-80: Adiciona campos de forma de pagamento e criado por no Agendamento
